name: anaka
favicon: null
layout_spectrum: 0.7740007201209664
typography_spectrum: 0.1364284527953714
title: 'elev8 .*. anünaka'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7496846793219447
  lightness: 0.7600935390219092
  saturation: 0.5578980599530041
  rhythmicContrast: 0.9990869674365968
purpose: []
