name: anaka
favicon: null
layout_spectrum: 0.45089
typography_spectrum: 0.92989
title: 'elev8 .*. anünaka'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#06060a'
    - '#172844'
    - '#5b241f'
    - '#824330'
    - '#b07e59'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.5578980599530041
  rhythmicContrast: 0.9990869674365968
purpose: []
