name: anaka
favicon: null
layout_spectrum: 1
typography_spectrum: 0.92989
title: 'elev8 .*. anünaka'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#312728'
    - '#ffffff'
    - '#ff5e56'
    - '#cabcb1'
    - '#3abe75'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.5578980599530041
  rhythmicContrast: 0.9990869674365968
purpose: []
